## Authors: Pablo Mollá, Pavlo Poliuha and Junjie Chen

# Getting started with numpy

- In this lab exercise we present the different functionnalities of numpy, particularly its algebra library. 
- The exercise's objective is to train you how to access, multiply and apply other operations on numpy matrix.


## Create a numpy array
First, the base type we will use in the remaining is the `numpy.array`object which is a multi-dimensional array (or a tensor). 
You can create an array giving a python list in arguments but also you can initialise it given specific shape, or instanciate it with zeros or ones.

- `np.array([[0,1,2], [3,4,5]])` create a 2-dimensional array having two lines and 3 columns
- `np.ndarray((5,3,4))` create a 3-dimensional array with shape 5, 3 and 4 (5 lines, 3 columns, 4 entries)
- `np.zeros(5,3,4)` create a 3-dimensional array with shape 5, 3 and 4 (5 lines, 3 columns, 4 entries) where each componenent is set two zeros

You also can fill the array with a specific value using the inplace operation `.fill(value)`. To access information on the different dimensions (size) you can use the array attribute `shape`.


## Access sub-part of the array
To access sub-part of a numpy array you can use index  surrounded by [], you can index on the different dimenssion using the comma between each dimensions:

* `x[1,5,3]` will select the element in the first line, the fith column and the third element on the array

In addition you can select slice, e.g. select the lines between a and b, using the `:` symbol:

* `x[2:5]` will select the lines 2, 3 and 4
* `x[2:]` will select elements from the second line to the last
*  `x[:-2]` will select the lines from the first to the last third.

We can combine the two last notations to select slices on different dimension:
* `x[2:5, :, :3]` will select the elements between the lines 2 to 5 and the first three elements on the last dimension

## Transpose dimension
To transpose dimension you can use the `transpose` numpy method taking in argument the index of the transposed dimension

In [1]:
import numpy as np
import math
import matplotlib

## Exercise 1 : Manipulate np.array

### **Question 1:** Create a variable `np_minus_three` containing a `np.array`of shape (2,5,10,2) (4 dimensions), where each componenent has the value `-3`. 

#### Option 1

In [21]:
# Empty variable (epsilon small with corresponding dimensions)
np_minus_three = np.empty((2, 5, 10, 2))

# Filling with value -3
np_minus_three.fill(-3)

np_minus_three

array([[[[-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.]],

        [[-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.]],

        [[-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.]],

        [[-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.]],

        [[-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.],
         [-3., -3.],
     

#### Option 2

In [22]:
# Both operations in a single line
np_minus_three_2 = np.full((2, 5, 10, 2), -3)

np_minus_three_2

array([[[[-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3]],

        [[-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3]],

        [[-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3]],

        [[-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3]],

        [[-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3],
         [-3, -3]]],


       [[[-3, -3],
         [-3, -3],


#### Checking 

These lines of code are using Python's assert statement to check two conditions:

- `np.all(np_minus_three == -3)`: This condition checks whether all elements in the np_minus_three array are equal to -3. It uses NumPy's np.all() function to check if all elements satisfy the condition np_minus_three == -3. If all elements are indeed equal to -3, this condition will return True, indicating that the array contains only the value -3.

- `np_minus_three.shape == (2,5,10,2)`: This condition checks whether the shape of the np_minus_three array matches the specified shape (2, 5, 10, 2). If the shape matches, this condition will return True.

In [16]:
assert(np.all(np_minus_three == -3))
assert(np_minus_three.shape == (2,5,10,2))


### **Question 2:** In the following create a variable `np_range` containing a `np.array`of shape (2,5) (2 dimensions), where the array contains the list of integer from 0 to 9 (included). The first line containing integer for 0 to 5, the second from 5 to 9. You should use the functions `np.arange` and the method `reshape` (**and no list!!!**).

In [17]:
# Generate a range of integers from 0 to 9
np_range = np.arange(10)

# Reshape the array to shape (2, 5)
np_range = np_range.reshape(2, 5)

np_range

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
assert(np.all(np_range == np.array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])))

### **Question 3:** Similarly create a variable `np_range_large` containing a `np.array`of shape (2,5,10,2) (4 dimensions), where the array contains the list of integer from 0 to 199 (included).

In [33]:
# Generate a range of integers from 0 to 199
np_range_large = np.arange(200)

# Reshape the array to shape (2, 5, 10, 2)
np_range_large = np_range_large.reshape(2, 5, 10, 2)

np_range_large

array([[[[  0,   1],
         [  2,   3],
         [  4,   5],
         [  6,   7],
         [  8,   9],
         [ 10,  11],
         [ 12,  13],
         [ 14,  15],
         [ 16,  17],
         [ 18,  19]],

        [[ 20,  21],
         [ 22,  23],
         [ 24,  25],
         [ 26,  27],
         [ 28,  29],
         [ 30,  31],
         [ 32,  33],
         [ 34,  35],
         [ 36,  37],
         [ 38,  39]],

        [[ 40,  41],
         [ 42,  43],
         [ 44,  45],
         [ 46,  47],
         [ 48,  49],
         [ 50,  51],
         [ 52,  53],
         [ 54,  55],
         [ 56,  57],
         [ 58,  59]],

        [[ 60,  61],
         [ 62,  63],
         [ 64,  65],
         [ 66,  67],
         [ 68,  69],
         [ 70,  71],
         [ 72,  73],
         [ 74,  75],
         [ 76,  77],
         [ 78,  79]],

        [[ 80,  81],
         [ 82,  83],
         [ 84,  85],
         [ 86,  87],
         [ 88,  89],
         [ 90,  91],
         [ 92,  93],
     

#### Checking

This code computes the SHA-256 hash of the string representation of the NumPy array `np_range_large` and compares it to a predefined hash value (`hash`). If the computed hash matches the predefined hash value, the `assert` statement passes; otherwise, it raises an `AssertionError`.

Here's what each part of the code does:

1. `hash = '5681936f8523b54ad2d46bf26e0bc6e6bc7379ce84eb0d78846db079596eabeb'`: This line defines a variable `hash` containing a SHA-256 hash value.

2. `import hashlib`: This line imports the `hashlib` module, which provides cryptographic hash functions.

3. `h = hashlib.new('sha256')`: This line creates a new SHA-256 hash object.

4. `h.update(str(np_range_large).encode('utf-8'))`: This line updates the hash object with the byte representation of the string obtained by converting `np_range_large` to a string using `str()` and encoding it using UTF-8.

5. `assert(hash == h.hexdigest())`: This line compares the computed SHA-256 hash value (`h.hexdigest()`) with the predefined hash value (`hash`). If they match, the `assert` statement passes silently. If they don't match, it raises an `AssertionError`.

In summary, this code verifies whether the SHA-256 hash of the string representation of the NumPy array `np_range_large` matches a predefined hash value. If they match, it indicates that the array has been serialized correctly.

In [27]:
hash = '5681936f8523b54ad2d46bf26e0bc6e6bc7379ce84eb0d78846db079596eabeb'
import hashlib
h = hashlib.new('sha256')
h.update(str(np_range_large).encode('utf-8'))
assert(hash == h.hexdigest())

### **Question 4:** From the previous array select the columns 4 and 5 into the variable `np_sub`

In [51]:
# Select columns 4 and 5 along the last dimension
np_sub = np_range_large[:, 3:5, :, :]

np_sub

array([[[[ 60,  61],
         [ 62,  63],
         [ 64,  65],
         [ 66,  67],
         [ 68,  69],
         [ 70,  71],
         [ 72,  73],
         [ 74,  75],
         [ 76,  77],
         [ 78,  79]],

        [[ 80,  81],
         [ 82,  83],
         [ 84,  85],
         [ 86,  87],
         [ 88,  89],
         [ 90,  91],
         [ 92,  93],
         [ 94,  95],
         [ 96,  97],
         [ 98,  99]]],


       [[[160, 161],
         [162, 163],
         [164, 165],
         [166, 167],
         [168, 169],
         [170, 171],
         [172, 173],
         [174, 175],
         [176, 177],
         [178, 179]],

        [[180, 181],
         [182, 183],
         [184, 185],
         [186, 187],
         [188, 189],
         [190, 191],
         [192, 193],
         [194, 195],
         [196, 197],
         [198, 199]]]])

In [52]:
hash = 'a1d90b458e5c3576b11b280526e27ecf0afa506f0238cf19f44d773f1d98330d'
h = hashlib.new('sha256')
h.update(str(np_sub).encode('utf-8'))
assert(hash == h.hexdigest())

### **Question 5:** Let us consider variable $x \in \mathbb{R}^{2 \times 1}$ and $W \in \mathbb{R}^{2 \times 4}$, compute the dot product in $y$ using a loop and the function `np.sum()`. Why the objective of the line 2 (`np.random.seed(42)`)?  What is $W$ in the case of a neural network layer?

- The objective of line 2, np.random.seed(42), is to set the random number generator to a fixed state. This ensures that the random numbers generated by np.random.rand are the same every time you run the code, which is essential for reproducibility of results.

- In the context of a neural network layer, W represents the weights of the connections between the neurons of two successive layers. When a dot product is computed between an input vector x and the weight matrix W, it results in a new vector y which can be considered as a transformed version of the input. This transformation is part of what allows neural networks to learn from data. ​

In [55]:
np.random.seed(42)

x = np.array([2.5, -6.2])
W = np.random.rand(2,4)
y = np.zeros(4)

for i in range(W.shape[1]):  # Loop over the columns of W
    y[i] = np.sum(x * W[:, i])  # Multiply x with each column of W and sum the products


In [57]:
x

array([ 2.5, -6.2])

In [58]:
W

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615]])

In [61]:
y

array([-0.03096527,  1.40961974,  1.46986646, -3.87364589])

In [56]:
hash = '70145392ec18208eb6aaccc15a752d819f10fa9c3dfcd2515d90acaa4a90b952'
h = hashlib.new('sha256')
h.update(str(y).encode('utf-8'))
assert(hash == h.hexdigest())

### **Question 6:** Let us consider variable $X \in \mathbb{R}^{10 \times 2}$, compute the dot product in $Y$ using a loop and the function `np.sum()` and the *Hadamard product* `*` for each line of $X$. 

The Hadamard product, also known as the element-wise product or Schur product, is an operation that takes two matrices of the same dimensions and produces another matrix where each element $i, j$ is the product of elements $i, j$ of the original two matrices. Mathematically, it is denoted as $A \circ B$ for two matrices $A$ and $B$ and is defined as:

- $(A \odot B)_{ij}$ = $(A)_{ij} \cdot (B)_{ij}$

If $A$ and $B$ are two matrices of the same size, their Hadamard product is another matrix $C$ of the same size as $A$ and $B$, and each element of $C$ is obtained by multiplying the corresponding elements of $A$ and $B$.


In [64]:
np.random.seed(42)

X = np.random.rand(10,2)
W = np.random.rand(2,4)
Y = np.zeros((10,4))

# Compute dot product using a loop and np.sum()
for i in range(X.shape[0]):  # Loop over the rows of X
    for j in range(W.shape[1]):  # Loop over the columns of W
        # Compute the Hadamard product for the i-th row of X and all rows of W,
        # then sum the results to get the element at (i, j) of Y
        Y[i, j] = np.sum(X[i, :] * W[:, j])

In [65]:
hash = '2f86a4d2697294307ab0099164c2aeeb4315876b97aba275f73cfac42d345d50'
h = hashlib.new('sha256')
h.update(str(Y).encode('utf-8'))
assert(hash == h.hexdigest())

## Exercise 2 : Matrix operation

The scalar product as implemented canbe costly, particularly in python where loops are poorly optimized. To this end a majority of algebra like libraries implement matrix operation using a C backend. 
Numpy also propose matrix operation, particularly it implement the matrix multiplication, the hadamard product and some other optimized matrix operations.

### 1. Hadamard product
The Hadamard produc given two matrix/tensors $A,B \in \mathbb{R}^{n  \times m}$ is denoted by $\odot$ where:
$$(A\odot B)_{i,j} = A_{i, j} B_{i,j}$$
Thus (with all matrix):
$$A \odot B = 
\begin{pmatrix}
A_{1,1}B_{1,1} & A_{1,2}B_{1,2} & \ldots & A_{1,m}B_{1,m} \\
A_{2,1}B_{2,1} & A_{2,2}B_{2,2} & \ldots & A_{2,m}B_{2,m} \\
\vdots & \vdots & \ddots & \vdots \\
A_{n,1}B_{n,1} & A_{n,2}B_{n,2} & \ldots & A_{n,m}B_{n,m} \\
\end{pmatrix}
$$

In numpy this operation is using the classical python multiplication symbol `*`, `A * B` being the Hadamard product of `A` and `B`.

### 2. Dot Product 
The Dot product is two matrix/tensors $A\in \mathbb{R}^{n  \times m}$ and $B \in \mathbb{R}^{m  \times l}$ is denoted by "$.$" where:
$$(A . B)_{i, j} = \sum\limits_{k=1}^{m} A_{i, k} B_{k,j}$$
Thus (picturing the whole matrix):
$$A . B = 
\begin{pmatrix}
\sum\limits_{k=1}^{m} A_{1, k} B_{k,1} & \sum\limits_{k=1}^{m} A_{1, k} B_{k,2} & \sum\limits_{k=1}^{m} A_{1, k} B_{k,l}\\
\sum\limits_{k=1}^{m} A_{2, k} B_{k,1} & \sum\limits_{k=1}^{m} A_{2, k} B_{k,2} & \sum\limits_{k=1}^{m} A_{2, k} B_{k,l} \\
\vdots & \vdots & \ddots & \vdots \\
\sum\limits_{k=1}^{m} A_{n, k} B_{k,1} & \sum\limits_{k=1}^{m} A_{m, k} B_{k,2} & \sum\limits_{k=1}^{m} A_{m, k} B_{k,l} \\
\end{pmatrix}
$$

In numpy this operation is use `@` operator, `A@B` being the dot product of `A` and `B`.

### 3. Outer Product (on vectors)
The outer product between two vectors $u\in \mathbb{R}^{n}$ and $v \in \mathbb{R}^{m}$ is denoted by $\otimes_{outer}$ where:
$$(u \otimes_{outer} v)_{i, j} = u_{i} v_{j}$$
Thus (picturing the whole matrix):
$$u\otimes_{outer}v =  \begin{pmatrix}
u_{1} \\
u_{2}\\
\vdots \\
u_{n}\\
\end{pmatrix}
\otimes_{outer}
\begin{pmatrix}
v_{1} &v_{2} & \ldots &v_{m} \\
\end{pmatrix} =
\begin{pmatrix}
u_{1}v_{1} & u_{1}v_{2} & \ldots & u_{1}v_{m} \\
u_{2}v_{1} & u_{2}v_{2} & \ldots & u_{2}v_{m} \\
\vdots & \vdots & \ddots & \vdots \\
u_{n}v_{1} & u_{n}v_{2} & \ldots & u_{n}v_{m} \\
\end{pmatrix}
$$

In numpy this operation is implemented with the `np.outer` function.



### **Question 1:** Let us consider variable $x \in \mathbb{R}^2$ and $W \in \mathbb{R}^{2 \times 4}$, compute $y$ resulting of the linear application (W) on $x$.

NB: You can look at the transpose method of numpy

In [70]:
np.random.seed(42)

x = np.array([2.5, -6.2])
W = np.random.rand(2,4)

# Option 1: Compute y as the result of the linear application (W) on x
y = x.T.dot(W)

# Option 2: Compute y as the result of the linear application (W) on x
y = x.T @ W



In [71]:
hash = '70145392ec18208eb6aaccc15a752d819f10fa9c3dfcd2515d90acaa4a90b952'
h = hashlib.new('sha256')
h.update(str(y).encode('utf-8'))
assert(hash == h.hexdigest())

### **Question 2:** Let us consider variable $X \in \mathbb{R}^{10 \times 2}$, compute the dot product  for each line of $X$ with $W$ into $Y$ with only one loop!

In [72]:
np.random.seed(42)

X = np.random.rand(10,2)
W = np.random.rand(2,4)
Y = np.zeros((10,4))

In [73]:
X

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452],
       [0.05808361, 0.86617615],
       [0.60111501, 0.70807258],
       [0.02058449, 0.96990985],
       [0.83244264, 0.21233911],
       [0.18182497, 0.18340451],
       [0.30424224, 0.52475643],
       [0.43194502, 0.29122914]])

In [74]:
W

array([[0.61185289, 0.13949386, 0.29214465, 0.36636184],
       [0.45606998, 0.78517596, 0.19967378, 0.51423444]])

In [80]:
for i in range(X.shape[0]):
    Y[i] = X[i].dot(W)
Y

array([[0.66275571, 0.79872407, 0.29925261, 0.62610725],
       [0.72090278, 0.57216091, 0.33338452, 0.57602546],
       [0.16660488, 0.14424679, 0.07672803, 0.13737703],
       [0.43057557, 0.688203  , 0.18992148, 0.46669722],
       [0.69072461, 0.63981342, 0.31699606, 0.58434091],
       [0.45494145, 0.76442131, 0.19967922, 0.50630242],
       [0.60617393, 0.2828442 , 0.28559222, 0.4141673 ],
       [0.19489542, 0.16936828, 0.08974026, 0.16092665],
       [0.42547715, 0.45446606, 0.19366284, 0.38131058],
       [0.39710768, 0.2889198 , 0.18434125, 0.30800823]])

### **Question 3:** Let us consider variable $X \in \mathbb{R}^{10 \times 2}$, compute the dot of $X$ with $W$ into $Y$ with no loop!

In [77]:
Y = X @ W
Y

array([[0.66275571, 0.79872407, 0.29925261, 0.62610725],
       [0.72090278, 0.57216091, 0.33338452, 0.57602546],
       [0.16660488, 0.14424679, 0.07672803, 0.13737703],
       [0.43057557, 0.688203  , 0.18992148, 0.46669722],
       [0.69072461, 0.63981342, 0.31699606, 0.58434091],
       [0.45494145, 0.76442131, 0.19967922, 0.50630242],
       [0.60617393, 0.2828442 , 0.28559222, 0.4141673 ],
       [0.19489542, 0.16936828, 0.08974026, 0.16092665],
       [0.42547715, 0.45446606, 0.19366284, 0.38131058],
       [0.39710768, 0.2889198 , 0.18434125, 0.30800823]])

## Exercise 3 : Apply a function

Numpy propose a large amount of [built-in functions](https://numpy.org/doc/stable/reference/routines.math.html) e.g. cosinus, tanh... By default those functions are applired piecewise. 

### **Question 1:** In this exercise the objective is to build a function $\mathcal{f} : \mathbb{R}^n \to ]0,1[$ such that 

$$
\mathcal{f}(x) = \frac{1}{1 + e^{-(w^{\intercal}x + b)}}
$$

With $w \in \mathbb{R}^{n}$, $x\in \mathbb{R}^{n}$ and $b \in \mathbb{R}$.
Create an object having as attribute $w$ and $b$ implementing the function in a method called forward

In [92]:
import random
class LinearClassifier(object):
    def __init__(self, dim=5):
        self.w = np.random.rand((dim))
        self.b = random.random()
    
    def forward(self, x):
        # Calculate the linear combination of weights and input, plus bias
        linear_combination = np.dot(self.w, x) + self.b
        # Apply the sigmoid function
        return 1 / (1 + np.exp(-linear_combination))      

dim = 5
x = np.random.rand((5))
classifier = LinearClassifier(dim)
f_x = classifier.forward(x)

In [93]:
f_x

0.927437000169336

### **Question 2:** In this exercise the objective is to build a function $\mathcal{g} : \mathbb{R} \times \mathbb{R} \to \mathbb{R}$ such that 
$$
\mathcal{g}(x, y) = -(ylog(x) + (1-y) log(1-x))
$$
Create an object implementing the function in a method called forward

In [94]:

class CrossEntropy(object):
    def __init__(self):
        pass
    
    def forward(self, x, y):
        return -(y * np.log(x) + (1-y) * np.log(1-x))   